version: '2'

services:
  drone-server:
    image: drone/drone:0.8.5

    ports:
      - 8000:8000
      - 9000:9000
    volumes:
      - /var/lib/drone:/var/lib/drone/
    restart: always
    environment:
      - DRONE_OPEN=false # So only I can log in!
      - DRONE_ADMIN=reisgesiane
      - DRONE_HOST=${DRONE_HOST}
      - DRONE_GITHUB=true
      - DRONE_GITHUB_CLIENT=${GITHUB_CLIENT}
      - DRONE_GITHUB_SECRET=${GITHUB_SECRET}
      - DRONE_SECRET=1234

  drone-agent:
    image: drone/agent:0.8

    command: agent
    restart: always
    depends_on:
      - drone-server
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DRONE_SERVER=drone-server:9000
      - DRONE_SECRET=1234
